# Generated by Django 3.0.9 on 2020-08-04 03:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inv_num', models.IntegerField()),
                ('inv_date', models.DateField(auto_now_add=True)),
                ('inv_duedate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=80)),
                ('item_description', models.CharField(max_length=200)),
                ('item_cost', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('tax', models.BooleanField(default=False)),
                ('inv_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Invoice')),
                ('inv_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='webapp.Item')),
            ],
        ),
    ]
